sudo: required
language: node_js
env:
  global:
  - REDIS_PORT_6379_TCP_ADDR=localhost
  - REDIS_PORT_6379_TCP_PORT=6379
node_js:
- '6'
services:
- docker
before_install:
- docker run -p 6379:6379 -d --name tree_redis redis:3.0.7-alpine
- docker run -p 8500:8500 -d --name tree_consul consul
script: nyc npm run test && nyc report --reporter=text-lcov | coveralls
deploy:
  - provider: npm
    email: thiago@cruxframework.org
    skip_cleanup: true
    api_key:
      secure: cfa0ccHd9C5MBQlRuz3m79uGyvo338PpBgL+xjrXrsz31oMa7TuzSMg43Oi6okWawxtladv3J7wPXI/Ic5Jrfgxa9Jd1/htmRoiAnWvztYv9JIjxhT6qx+UpLCKXLj+rcGPrBZrfsdthSa0hK0dqV1KMQUKgZPnefxL+ROm9J30EQxkoBVaB6EG5VhSJSGcVmFrxDgcjef/7bwquRBtCXr/K3dMRrK5qM/tQAmqKsz8MDdHcr5zqV9rydiehtX0Tb1FcxJ3Jy+uh/HOS2TC+KXIKB9qBVg2tj7vOKZcPIpL4Ag6McUOH5gAhV+fIfKMn964d6wwGMZ6OE3aJB4FEYWTBEaGSf76rQBWSvNLS/aK1oicvGI8Xq9dye6BM9OT1MqkbbD1bTQzhsISYIcO5I8Do6hFYeDTwwscYsNxFZ2S17OukHJ0C7BWpEQ8HX1r3315lyuCi6exRbwzWMKRCIsHns9P5hT6JBuWCa0Z2k6WbxKjoar4H2sVYPdzZvdBdxXxP0lxnEFCt9STPuQq6Vc93IwBCQUYkfY3RZS2xZLwS4tcZ3/GBAKQzbFvLkM7FISnZeUkx3EWclooNk82Rgg1gSe49YJ3nidjQac1lyb0nseDsQvh38LEx7jIs0OrObPm/fQ575XSCPrxAyZMfSCRPBVOa4CBSBLbNx9mjHDU=
    on:
      tags: true
      repo: Leanty/tree-gateway
  - provider: script
    skip_cleanup: true
    script: deploy-docker.sh
    on:
      tags: true
      repo: Leanty/tree-gateway
