sudo: required
language: node_js
env:
  - REDIS_PORT_6379_TCP_ADDR=localhost REDIS_PORT_6379_TCP_PORT=6379
node_js:
  - '5'
services:
  - docker
before_install:
  - docker run -p 6379:6379 -d --name tree_redis redis:3.0.7-alpine
  - npm install -g gulp
script: gulp release
