sudo: required
language: node_js
env:
  - REDIS_PORT_6379_TCP_ADDR=localhost REDIS_PORT_6379_TCP_PORT=6379
node_js:
  - '6'
services:
  - docker
before_install:
  - docker run -p 6379:6379 -d --name tree_redis redis:3.0.7-alpine
  - docker run -p 8500:8500 -d --name tree_consul consul
script: nyc npm run test && nyc report --reporter=text-lcov | coveralls
